### ISSUE TITLE
Entering zero then parenthesis, or decimal then parenthesis causes the application to crash.

### ISSUE THREAD

**Issue by src52** [Darkempire78/OpenCalc#106]
Steps to reproduce:

1. Open OpenCalc.
2. Press the zero button (or the decimal . button)
3. Press the parenthesis button

The application will crash with a runtime exception: "Unexpected: 0", and "Unexpected: (".

OS: Graphene OS, Android 13.

**Comment by Darkempire78** [comment]
What is the version of OpenCalc ?

**Comment by src52** [comment]
> What is the version of OpenCalc ?

Ah, apologies. Should've mentioned.

2.0.0-beta 2.

Here's the crash log.

`type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/2022111800:user/release-keys
package: com.darkempire78.opencalculator:22
process: com.darkempire78.opencalculator
processUptime: 4933 + 175 ms

java.lang.RuntimeException: Unexpected: 0
	at com.darkempire78.opencalculator.Calculator$evaluate$1.parse(Calculator.kt:37)
	at com.darkempire78.opencalculator.Calculator.evaluate(Calculator.kt:127)
	at com.darkempire78.opencalculator.MainActivity$updateResultDisplay$1.invokeSuspend(MainActivity.kt:239)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4088194, Dispatchers.Default]
`

**Comment by ctntt** [comment]
Also the app crashes if you 

1. Open OpenCalc
2. Press the '%' button 
3. Press the parenthesis button '()'

and if you

1. Open OpenCalc
2. Press the 'INV' button 
3. Press the 'e^' button


OS: LineageOS, Android 12
Version: 2.0.0-beta2
