### ISSUE TITLE
App crash on tablet

### ISSUE THREAD

**Issue by odmfl** [Darkempire78/OpenCalc#190]
The app when used on a tablet causes a crash if you do an operation and press the = key

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.darkempire78.opencalculator.debug, PID: 20588
    java.lang.NullPointerException: itemView.findViewById(R.id.history_time) must not be null
        at com.darkempire78.opencalculator.HistoryAdapter$HistoryViewHolder.<init>(HistoryAdapter.kt:53)
        at com.darkempire78.opencalculator.HistoryAdapter.onCreateViewHolder(HistoryAdapter.kt:23)
        at com.darkempire78.opencalculator.HistoryAdapter.onCreateViewHolder(HistoryAdapter.kt:14)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:861)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:809)
        at android.view.View.layout(View.java:22873)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3485)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2953)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1958)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8246)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
        at android.view.Choreographer.doCallbacks(Choreographer.java:878)
E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:811)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7791)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by Darkempire78** [comment]
Use the issue template please (I need your version, etc...)

**Comment by odmfl** [comment]
You can reproduce the same error if you use the android studio emulator by choosing a tablet as device

i don't know where to find issue template, Anyway:
Device: Lenovo tab p11
Android 11 version
app version 2.1.2

**Comment by odmfl** [comment]
I tried other versions, with version 2.0.0 the error does not appear.  The error occurs from version 2.1.1 and higher.  I don't understand what the error is and why it only shows up on tablets.  However it has to do with HistoryAdapter.kt
