### ISSUE TITLE
Crashes on rotate

### ISSUE THREAD

**Issue by jf916** [Darkempire78/OpenCalc#303]
**Describe the bug**
When your phone is rotated the app crashes

**To Reproduce**
1. Open the app
2. Rotate your phone
3. See error

**Expected behavior**
The app is not suppost to crash

**Screenshots/videos**
![Screenshot_20230801-233014_jOS Launcher.png](https://github.com/Darkempire78/OpenCalc/assets/62702353/5989c4b5-a8e6-4896-a99e-9b67bc6bd9fe)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Lineage OS 20 (android 13)
 - Version latest beta
 - Language English

**Additional context**

**Comment by Darkempire78** [comment]
Does anyone have an idea of how to fix that ?

**Comment by mwadle** [comment]
The crash dump look pretty descriptive. It looks like it might relate to having multiple views called id/divideButton. I'll look into it more tonight if I have time after entering new issues, but if I don't get to it tonight I probably won't get to it anytime soon.

Pasting the crash dump below:

FATAL EXCEPTION: main
                                                                                                    Process: com.darkempire78.opencalculator, PID: 3392
                                                                                                    java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class k1.b instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/divideButton. Make sure other views do not use the same id.
                                                                                                    	at android.view.View.onRestoreInstanceState(View.java:21193)
                                                                                                    	at android.view.View.dispatchRestoreInstanceState(View.java:21165)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4064)
                                                                                                    	at android.view.View.restoreHierarchyState(View.java:21143)
                                                                                                    	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2221)
                                                                                                    	at android.app.Activity.onRestoreInstanceState(Activity.java:1745)
                                                                                                    	at android.app.Activity.performRestoreInstanceState(Activity.java:1698)
                                                                                                    	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1391)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3834)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2346)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:349)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8262)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
