### ISSUE TITLE
Starting activity from TileService using an Intent is not allowed.

### ISSUE THREAD

**Issue by bashuser30** [Darkempire78/OpenCalc#415]
**Describe the bug**
I am unable to launch the app using the Quick Tile.

**To Reproduce**
1. Click on the tile.
2. Get error and logs.

**Expected behavior**
App opens from tile press.

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Graphene OS, Android 14
 - App version: 3.0.0-beta4
 - Language: English

**Additional context**
Here are logs from the crash:

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024011600:user/release-keys
package: com.darkempire78.opencalculator:42
process: com.darkempire78.opencalculator
processUptime: 2317 + 273 ms
installer: com.machiav3lli.fdroid

java.lang.UnsupportedOperationException: startActivityAndCollapse: Starting activity from TileService using an Intent is not allowed.
    at android.service.quicksettings.TileService.startActivityAndCollapse(TileService.java:355)
    at com.darkempire78.opencalculator.MyTileService.onClick(Unknown Source:21)
    at android.service.quicksettings.TileService$H.handleMessage(TileService.java:494)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8279)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by inson1** [comment]
Its bug, because of the new android version 

https://stackoverflow.com/questions/77547985/launch-an-activity-from-tileservice-for-android-14-is-not-allowed

**Comment by muryno** [comment]
I have a fix for this here [MR](https://github.com/Darkempire78/OpenCalc/pull/424)
